# Generated by Django 3.2.5 on 2021-07-25 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=200)),
                ('poster_url', models.CharField(max_length=500)),
                ('rating_aud', models.CharField(max_length=200)),
                ('rating_cri', models.CharField(max_length=200)),
                ('rating_net', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('showtimes', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField()),
                ('comment_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.movies')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
