# Generated by Django 3.2.5 on 2021-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kor', models.CharField(max_length=200)),
                ('title_eng', models.CharField(max_length=200)),
                ('poster_url', models.CharField(max_length=500)),
                ('rating_aud', models.CharField(max_length=200)),
                ('rating_cri', models.CharField(max_length=200)),
                ('rating_net', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('showtimes', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
